import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Urbanist } from 'next/font/google'

const inter = Inter({ subsets: ["latin"] });
const urbanist = Urbanist({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-Urbanist',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.variable}`}>{children}</body>
    </html>
  );
}
